
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: python:3.9-slim
      script: |
        # Remove unnecessary files
        rm -rf __pycache__
        rm -rf .pytest_cache
        echo "Cleanup completed."
